from .homestead import Homestead
from opcodes.opcode import Opcode


class TangerineWhistle(Homestead):
    STOP = Homestead.STOP
    ADD = Homestead.ADD
    MUL = Homestead.MUL
    SUB = Homestead.SUB
    DIV = Homestead.DIV
    SDIV = Homestead.SDIV
    MOD = Homestead.MOD
    SMOD = Homestead.SMOD
    ADDMOD = Homestead.ADDMOD
    MULMOD = Homestead.MULMOD
    EXP = Homestead.EXP
    SIGNEXTEND = Homestead.SIGNEXTEND
    LT = Homestead.LT
    GT = Homestead.GT
    SLT = Homestead.SLT
    SGT = Homestead.SGT
    EQ = Homestead.EQ
    ISZERO = Homestead.ISZERO
    AND = Homestead.AND
    OR = Homestead.OR
    XOR = Homestead.XOR
    NOT = Homestead.NOT
    BYTE = Homestead.BYTE
    SHA3 = Homestead.SHA3
    ADDRESS = Homestead.ADDRESS
    BALANCE = Opcode("BALANCE", 400, 0x31)
    ORIGIN = Homestead.ORIGIN
    CALLER = Homestead.CALLER
    CALLVALUE = Homestead.CALLVALUE
    CALLDATALOAD = Homestead.CALLDATALOAD
    CALLDATASIZE = Homestead.CALLDATASIZE
    CALLDATACOPY = Homestead.CALLDATACOPY
    CODESIZE = Homestead.CODESIZE
    CODECOPY = Homestead.CODECOPY
    GASPRICE = Homestead.GASPRICE
    EXTCODESIZE = Opcode("EXTCODESIZE", 700, 0x3B)
    EXTCODECOPY = Opcode("EXTCODECOPY", 700, 0x3C)
    BLOCKHASH = Homestead.BLOCKHASH
    COINBASE = Homestead.COINBASE
    TIMESTAMP = Homestead.TIMESTAMP
    NUMBER = Homestead.NUMBER
    DIFFICULTY = Homestead.DIFFICULTY
    GASLIMIT = Homestead.GASLIMIT
    POP = Homestead.POP
    MLOAD = Homestead.MLOAD
    MSTORE = Homestead.MSTORE
    MSTORE8 = Homestead.MSTORE8
    SLOAD = Opcode("SLOAD", 200, 0x54)
    SSTORE = Homestead.SSTORE
    JUMP = Homestead.JUMP
    JUMPI = Homestead.JUMPI
    PC = Homestead.PC
    MSIZE = Homestead.MSIZE
    GAS = Homestead.GAS
    JUMPDEST = Homestead.JUMPDEST
    PUSH1 = Homestead.PUSH1
    PUSH2 = Homestead.PUSH2
    PUSH3 = Homestead.PUSH3
    PUSH4 = Homestead.PUSH4
    PUSH5 = Homestead.PUSH5
    PUSH6 = Homestead.PUSH6
    PUSH7 = Homestead.PUSH7
    PUSH8 = Homestead.PUSH8
    PUSH9 = Homestead.PUSH9
    PUSH10 = Homestead.PUSH10
    PUSH11 = Homestead.PUSH11
    PUSH12 = Homestead.PUSH12
    PUSH13 = Homestead.PUSH13
    PUSH14 = Homestead.PUSH14
    PUSH15 = Homestead.PUSH15
    PUSH16 = Homestead.PUSH16
    PUSH17 = Homestead.PUSH17
    PUSH18 = Homestead.PUSH18
    PUSH19 = Homestead.PUSH19
    PUSH20 = Homestead.PUSH20
    PUSH21 = Homestead.PUSH21
    PUSH22 = Homestead.PUSH22
    PUSH23 = Homestead.PUSH23
    PUSH24 = Homestead.PUSH24
    PUSH25 = Homestead.PUSH25
    PUSH26 = Homestead.PUSH26
    PUSH27 = Homestead.PUSH27
    PUSH28 = Homestead.PUSH28
    PUSH29 = Homestead.PUSH29
    PUSH30 = Homestead.PUSH30
    PUSH31 = Homestead.PUSH31
    PUSH32 = Homestead.PUSH32
    DUP1 = Homestead.DUP1
    DUP2 = Homestead.DUP2
    DUP3 = Homestead.DUP3
    DUP4 = Homestead.DUP4
    DUP5 = Homestead.DUP5
    DUP6 = Homestead.DUP6
    DUP7 = Homestead.DUP7
    DUP8 = Homestead.DUP8
    DUP9 = Homestead.DUP9
    DUP10 = Homestead.DUP10
    DUP11 = Homestead.DUP11
    DUP12 = Homestead.DUP12
    DUP13 = Homestead.DUP13
    DUP14 = Homestead.DUP14
    DUP15 = Homestead.DUP15
    DUP16 = Homestead.DUP16
    SWAP1 = Homestead.SWAP1
    SWAP2 = Homestead.SWAP2
    SWAP3 = Homestead.SWAP3
    SWAP4 = Homestead.SWAP4
    SWAP5 = Homestead.SWAP5
    SWAP6 = Homestead.SWAP6
    SWAP7 = Homestead.SWAP7
    SWAP8 = Homestead.SWAP8
    SWAP9 = Homestead.SWAP9
    SWAP10 = Homestead.SWAP10
    SWAP11 = Homestead.SWAP11
    SWAP12 = Homestead.SWAP12
    SWAP13 = Homestead.SWAP13
    SWAP14 = Homestead.SWAP14
    SWAP15 = Homestead.SWAP15
    SWAP16 = Homestead.SWAP16
    LOG0 = Homestead.LOG0
    LOG1 = Homestead.LOG1
    LOG2 = Homestead.LOG2
    LOG3 = Homestead.LOG3
    LOG4 = Homestead.LOG4
    CREATE = Homestead.CREATE
    CALL = Opcode("CALL", 700, 0xF1)
    CALLCODE = Opcode("CALLCODE", 700, 0xF2)
    RETURN = Homestead.RETURN
    SELFDESTRUCT = Opcode("SELFDESTRUCT", 5000, 0xFF)
    DELEGATECALL = Opcode("DELEGATECALL", 700, 0xF4)
